name: $(BuildDefinitionName)_[$(Date:ddMMyyyy)]

pool:
  vmImage: 'Ubuntu 20.04'

trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true
  
variables:
  imageName: 'gr00vysky/docker-arm-api:latest'
  dockerFirstPart: docker run -e APP_ID=$(APP_ID) -e APP_KEY=$(APP_KEY) -e TENANT_ID=$(TENANT_ID) -e SUBSCRIPTION_ID=$(SUBSCRIPTION_ID)

steps:
- bash: |
    $(dockerFirstPart) -e RESOURCE_GROUP=$(RESOURCE_GROUP) -e METHOD="GET" -e RESOURCE_API="2018-10-01" -e RESOURCE_TYPE="ContainerInstance/containerGroups" -e -i $(imageName)
  displayName: 'get a list of Container Instances'

- bash: |
    $(dockerFirstPart) -e RESOURCE_GROUP=$(RESOURCE_GROUP) -e METHOD="DELETE" -e RESOURCE_API="2018-10-01" -e RESOURCE_TYPE="ContainerInstance/containerGroups" -e RESOURCE_NAME="azure-docker-agent-00" -i $(imageName)
  displayName: 'delete Container Instance'

- bash: |
    sleep 10
  displayName: 'wait 10 seconds'

- bash: | 
    $(dockerFirstPart) -e RESOURCE_GROUP=$(RESOURCE_GROUP) -e TEMPLATE_URI=$(TEMPLATE_URI) -e PARAMETERS_URI=$(PARAMETERS_URI) -e METHOD="ARM" -e RESOURCE_API="2019-10-01" -e RESOURCE_TYPE="Resources/deployments" -i $(imageName)
  displayName: 'create Container Instance'

- bash: |
    $(dockerFirstPart) -e RESOURCE_GROUP=$(RESOURCE_GROUP) -e METHOD="POST" -e RESOURCE_API="2018-10-01" -e RESOURCE_TYPE="ContainerInstance/containerGroups" -e RESOURCE_NAME="azure-docker-agent-00" -e APPEND_PARAM="/restart" -i $(imageName)
  displayName: 'restart Container Instance'
