apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-agent
  labels:
    app: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
      name: devops-agent
    spec:
      hostPID: false
      hostIPC: false
      securityContext:
        fsGroup: 1100
      containers:
        - name: devops-agent
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1100
            runAsGroup: 1100
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /temp
              name: tmp-volume
            - mountPath: /azp
              name: azp-volume
          image: ghcr.io/groovy-sky/devops-build-agent:latest
          command: ['sh', '-c', 'cp start.sh /temp/ && cd /temp && ./start.sh']
          env:
            - name: TMPDIR
              value: /tmp
            - name: AZP_URL
              value: "https://dev.azure.com/3ap9lq"
            - name: AZP_AGENT_NAME
              value: "devops-agent"
            - name: AZP_POOL
              value: "aks-pool"
            - name: AZP_TOKEN
              valueFrom: 
                secretKeyRef:
                  key: AZP_TOKEN
                  name: devops-secrets
      volumes:
      - name: azp-volume
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
