apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-agent
  labels:
    app: devops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-agent
  template:
    metadata:
      labels:
        app: devops-agent
    spec:
      hostPID: false
      hostIPC: false
      securityContext:
        fsGroup: 5000
      containers:
      - image: ghcr.io/groovy-sky/devops-build-agent:latest
        imagePullPolicy: Always
        name: devops-agent
        command: ['sh', '-c', 'cp ./start.sh ./agent/ && cd ./agent && ./start.sh']
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/3ap9lq"
          - name: AZP_AGENT_NAME
            value: "devops-agent"
          - name: AZP_POOL
            value: "aks-pool"
          - name: AZP_TOKEN
            valueFrom: 
              secretKeyRef:
                key: AZP_TOKEN
                name: devops-secrets
          - name: TMPDIR
            value: /temp
        volumeMounts:
        - mountPath: /agent
          name: agent-volume
        - mountPath: /temp
          name: temp-volume
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "100Mi"
            cpu: "100m"
        securityContext:
          capabilities:
            drop:
              - all
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 5000
          runAsGroup: 5000
      volumes:
      - name: temp-volume
        emptyDir: {}
      - name: agent-volume
        emptyDir: {}
